% get all the data together to define ITER

clear all;clf
addpath /home/dokuka/STRUCT_JO
addpath /home/dokuka/STRUCT_JO/iter
addpath /home/lister/matlab/xmltree

% Vladimir makes the data available

eval(['init_iter'])
tok = 'iter'
load tokamak.mat

% now load Yuri's data
readiterxls

% overwrite Vladimir's data
blockcontours1 = [3.6 3.6 3.9 3.9 3.6 ;-2.3 -1.5 -1.5 -2.3 -2.3]
blockcontours2 = [3.6 3.6 3.9 4.1 3.6;-2.9 -2.3 -2.3 -2.9 -2.9]
blockcontours3 = [7.4 7.9 8.2 7.8 7.4; -2.6 -1.8 -1.8 -2.6 -2.6]
blockcontours4 = [6.5 7.6 7.8 7.5 6.5; -3.15 -2.6 -2.6 -3.15 -3.15]
blockcontours5 = [6.8 6.6 7.6 7.3 6.8; -3.5 -3.15 -3.15 -3.5 -3.5]

% GENERAL
dina.general.title='ITER';
dina.general.description = ['DINA electromagnetic description of ' upper(tok)]
dina.general.doc='http://crppwww.epfl.ch';
dina.general.shortname='iter';
dina.general.update{1}.author='Jo Lister';
dina.general.update{1}.date='22-Sept-2004';
dina.general.update{1}.comment=['First version, autogenerated data taken from Vladmir'...
' Dokuka and supplemented by data from DINA'];
dina.general.update{2}.author='Jo Lister';
dina.general.update{2}.date=datestr(now);
dina.general.update{2}.comment=['Updated by Y. Gribov data "ITER I10"'];

% VESSEL
dina.vessel.title = 'Vacuum vessel'
dina.vessel.description = 'Vacuum vessel description'
dina.vessel.doc='http://crppwww.epfl.ch';

rho = 0.825e-6;
rs = innerr([end 1:end 1]);
zs = innerz([end 1:end 1]);
cr = (rs(1:end-1)+rs(2:end))/2;
cz = (zs(1:end-1)+zs(2:end))/2;
w = 0.06;
for i=1:length(innerr)
  dina.vessel.turn{i}.name=['VVI' iii(i,3)];
  dina.vessel.turn{i}.id=i;
  dina.vessel.turn{i}.type='contour';
  dl = abs((cr(i+1)-cr(i))+sqrt(-1)*(cz(i+1)-cz(i)));
  dina.vessel.turn{i}.area=dl*w;
  dina.vessel.turn{i}.res=2*pi*rs(i+1)*rho/dl/w;
  ang1 = atan2(zs(i+2)-zs(i),rs(i+1)-rs(i))-pi/2;
  ang2 = atan2(zs(i+2)-zs(i),rs(i+1)-rs(i))-pi/2;  
  contour = ...
  [cr(i)+w/2*cos(ang1)*[-1 1] cr(i+1)+w/2*cos(ang2)*[1 -1] cr(i)+w/2*cos(ang1)*[-1];...
   cz(i)+w/2*sin(ang1)*[-1 1] cz(i+1)+w/2*sin(ang2)*[1 -1] cz(i)+w/2*sin(ang1)*[-1] ];
  dina.vessel.turn{i}.contour = standardvec(contour);
end

rs = outerr([end 1:end 1]);
zs = outerz([end 1:end 1]);
cr = (rs(1:end-1)+rs(2:end))/2;
cz = (zs(1:end-1)+zs(2:end))/2;
w = 0.06;
for i=1:length(outerr)
  ind = i+length(innerr);
  dina.vessel.turn{ind}.name=['VVO' iii(ind,3)];
  dina.vessel.turn{ind}.id=ind;
  dina.vessel.turn{ind}.type='contour';
  dl = abs((cr(i+1)-cr(i))+sqrt(-1)*(cz(i+1)-cz(i)));
  dina.vessel.turn{ind}.area=dl*w;
  dina.vessel.turn{ind}.res=2*pi*rs(i+1)*rho/dl/w;
  ang1 = atan2(zs(i+1)-zs(i),rs(i+1)-rs(i))-pi/2;
  ang2 = atan2(zs(i+1)-zs(i),rs(i+1)-rs(i))-pi/2;  
  contour = ...
  [cr(i)+w/2*cos(ang1)*[-1 1] cr(i+1)+w/2*cos(ang2)*[1 -1] cr(i)+w/2*cos(ang1)*[-1];...
   cz(i)+w/2*sin(ang1)*[-1 1] cz(i+1)+w/2*sin(ang2)*[1 -1] cz(i)+w/2*sin(ang1)*[-1] ];
  dina.vessel.turn{ind}.contour = standardvec(contour);
end

for i=[127:131] 
   ind = length(innerr)+length(outerr)+i-126 ;
  dina.vessel.turn{ind}.name=['STRUC' iii(i-126,3)];
  dina.vessel.turn{ind}.id=ind;
  dina.vessel.turn{ind}.type='contour';
  dina.vessel.turn{ind}.area=tokamak.vessel.dr(i)*tokamak.vessel.dz(i);
  dina.vessel.turn{ind}.res=tokamak.vessel.res(i);
  switch i
  case 127, dina.vessel.turn{ind}.contour=standardvec(blockcontours1);
  case 128, dina.vessel.turn{ind}.contour=standardvec(blockcontours2);
  case 129, dina.vessel.turn{ind}.contour=standardvec(blockcontours3);
  case 130, dina.vessel.turn{ind}.contour=standardvec(blockcontours4);
  case 131, dina.vessel.turn{ind}.contour=standardvec(blockcontours5);
  end %switch
end

%PFCOILS
dina.pfcoils.title = 'PF Coils'
dina.pfcoils.description = 'PF Coils'
dina.pfcoils.doc='http://crppwww.epfl.ch';

for i=1:length(tokamak.coils.r)
  dina.pfcoils.coil{i}.name=coils(i);
  dina.pfcoils.coil{i}.id=i;
  dina.pfcoils.coil{i}.type='rzdrdz'; 
  dina.pfcoils.coil{i}.res=0;
  dina.pfcoils.coil{i}.turns = ntcoils(i);
  dina.pfcoils.coil{i}.rzdrdz=standardvec([rcoils(i) zcoils(i) drcoils(i) dzcoils(i)]);
end

%PFCIRCUITS
dina.pfcircuits.title = 'PF Circuits'
dina.pfcircuits.description = 'PF Circuits description'
dina.pfcircuits.doc='http://crppwww.epfl.ch';

for i=1:10
  dina.pfcircuits.circuit{i}.name=coils(i);
  dina.pfcircuits.circuit{i}.id=i;
  dina.pfcircuits.circuit{i}.type='n/a'; 
  dina.pfcircuits.circuit{i}.coilconnect=standardvec(i); 
  dina.pfcircuits.circuit{i}.supplyconnect=standardvec(i); 
end
i=11;
  dina.pfcircuits.circuit{i}.name='VS';
  dina.pfcircuits.circuit{i}.id=i;
  dina.pfcircuits.circuit{i}.type='n/a'; 
  dina.pfcircuits.circuit{i}.coilconnect=standardvec([8 -11]); 
  dina.pfcircuits.circuit{i}.supplyconnect=standardvec(i); 

%PFSUPPLIES
dina.pfsupplies.title = 'PF Supplies'
dina.pfsupplies.description = 'PF Supplies'
dina.pfsupplies.doc='http://crppwww.epfl.ch';

for i=1:10
  dina.pfsupplies.supply{i}.name=coils(i);
  dina.pfsupplies.supply{i}.id=i;
  dina.pfsupplies.supply{i}.type='thyr'; 
  dina.pfsupplies.supply{i}.imax=imaxeob(i);
  dina.pfsupplies.supply{i}.imin=-imaxeob(i);
  dina.pfsupplies.supply{i}.umax=umax(i);
  dina.pfsupplies.supply{i}.umin=-umax(i);
  dina.pfsupplies.supply{i}.delay=0.6e-3;
  dina.pfsupplies.supply{i}.tau=0.2e-3;
  dina.pfsupplies.supply{i}.res=tokamak.coils.res(i);
end

i=11;
dina.pfsupplies.supply{i}.name='VS';
dina.pfsupplies.supply{i}.id=i;
dina.pfsupplies.supply{i}.type='thyr'; 
dina.pfsupplies.supply{i}.imax=10e3;
dina.pfsupplies.supply{i}.imin=-10e3;
dina.pfsupplies.supply{i}.umax=10e3;
dina.pfsupplies.supply{i}.umin=-10e3;
dina.pfsupplies.supply{i}.delay=0.6e-3;
dina.pfsupplies.supply{i}.tau=0.2e-3;
dina.pfsupplies.supply{i}.res=0;

% MAGDIAG
dina.magdiag.title = 'Magnetic diagnostics'
dina.magdiag.description = 'Magnetic diagnostics description'
dina.magdiag.doc='http://crppwww.epfl.ch';

for i=1:length(tokamak.probes.r)
  dina.magdiag.bpol{i}.name=['BP' iii(i)];
  dina.magdiag.bpol{i}.id=i;
  dina.magdiag.bpol{i}.type='TBD';
  dina.magdiag.bpol{i}.r=tokamak.probes.r(i);
  dina.magdiag.bpol{i}.z=tokamak.probes.z(i);
  dina.magdiag.bpol{i}.area=0;
  dina.magdiag.bpol{i}.length=0;
  dina.magdiag.bpol{i}.polangle=tokamak.probes.theta(i)*pi/180;
  dina.magdiag.bpol{i}.torangle=0;
  dina.magdiag.bpol{i}.turns=1;
end

rref = [0 tokamak.loops.r(1)+0*tokamak.loops.r(2:end)];
zref = [0 tokamak.loops.z(1)+0*tokamak.loops.z(2:end)];
for i=1:length(tokamak.loops.r)
  dina.magdiag.dflux{i}.name=['FL' iii(i)];
  dina.magdiag.dflux{i}.id=i;
  dina.magdiag.dflux{i}.type='diff';
  dina.magdiag.dflux{i}.r12=standardvec([tokamak.loops.r(i) rref(i)]);
  dina.magdiag.dflux{i}.z12=standardvec([tokamak.loops.z(i) zref(i)]);
  dina.magdiag.dflux{i}.torangle=2*pi;
end

% LIMITER
dina.limiter.title = 'Limiter'
dina.limiter.description = 'Limiter outline description'
dina.limiter.doc='http://crppwww.epfl.ch';
dina.limiter.method='contour';
dina.limiter.r=standardvec(rlim');
dina.limiter.z=standardvec(zlim');

tok2 = dina.general.shortname

disp('Saving...')
tree=struct2xml(dina);
save(tree,['dina' tok2 '.xml']);

% make a gif file for adding to the html
clf;plot_tokamak(tok2);gif_make([tok2 '2xml'])

% the following line needs the Java Virtual Machine
fullfile = xslt(['dina' tok2 '.xml'],'dina2htm.xsl',['dina' tok2 '.htm'])

% this line is OK under mat65
web(fullfile,'-browser')

return

