disp(' ')
disp('====================================================================')
disp(' ')
disp('List of symbols print during code execution:')
disp(' ')
disp('1) at initialisation of data set:')
disp('    "#"  = ECRH modulation detection: no modulation')
disp('    "."  = progresse in loop for data initialisation')
disp('    "="  = ECRH modulation detection: no transition')
disp('    "^"  = ECRH modulation detection: transition off to on')
disp('    "_"  = ECRH modulation detection: systzm off')
disp('    "v"  = ECRH modulation detection: transition on to off')
disp('    "M"  = LCFS given by moments')
disp('    "S"  = LCFS givne by points')
disp(' ')
disp('2) during simulation execution:')
disp('    "!"  = non convergence of current diffusion equation for some time slice, try aletrnative method')
disp('    "#"  = LHCD efficiency identification: backup to previous value and step reduction')
disp('    "&"  = non convergence of two point model for some time slices: null traget temperature')
disp('    "."  = progresse of the convergence in loop')
disp('    ":"  = non convergence of two point model for some time slices')
disp('    "@:" = start of convergence loop (waveform relaxation) ')
disp('    "^"  = LHCD efficiency identification: increase of efficiency')
disp('    "v"  = LHCD efficiency identification: decrease of efficiency')
disp('    "~"  = slow convergence')
disp('    "B"  = B0 or PHI data inconsistency.')
disp('    "D"  = disruption flag')
disp('    "E"  = mismatch between pressure profiles and zerod energy content')
disp('    "F"  = non convergence of computation of fast particule energy content')
disp('    "He" = non convergence in He content computation or too much He in the discharge')
disp('    "I"  = plasma current overdrive (Ip > 2 * Ip_reference) ') 
disp('    "m"  = morphing exponent problem')
disp('    "M"  = morphing data inconsistency (problem with plasma shape).')
disp('    "0"  = coordinate transform problem')
disp('    "Q"  = NaN in Q profile; vlaue corrected using alternative method')
disp('    "S"  = unvalid LCFS given by points')
disp('    "T"  = no signal toolbox available, use alternative functions. May hav some accuracy problem')
disp('    "W"  = problem to compute flux surface averaged quatities')
disp('    "X"  = non convergence of current diffusion equation for some time slices')
disp('    "Y"  = no convergence of ICRH model in the whole simulation')
disp('    "Cn" = element no yet implemented in noncoronal model with n = number of charge of element or element symbol')
disp('    "c"  = problem to compute sawtooth trigger ')
disp('    "e"  = non convergence of equipartition computation ')
disp('    "i"  = profiles and zerod data initialisation ')
disp('    "s"  = problem to compute profiles after sawtooth reconnexion  ')
disp('    "x"  = non convergence of current diffusion equation for one time slice')
disp('    "o"  = no ICRH resonance in the plasma')
disp('    "b"  = noncoronal radiative data are missing for boron');
disp('    "q"  = ripple power lost in WEST for fast boron ions accelerated by ICRH is not available');
disp('    "y"  = no convergence of ICRH model for one time slice')
disp('     N   = "2"..."9": no convergence of ICRH model for N time slices')
disp('     t   = problem in computing tau_E from external data Te and Ti for some time slices');
disp('     >   = electron density profile corrected of imag and NaN');
disp('     <   = electron density profile corrected of negative value');

disp('  ')  
disp('3) in evolution mode (symbol before "@:"):')
disp('    "E"         = evolution mode')
disp('    "$"         = use LCFS given by points')
disp('    "+"         = adding time slice')
disp('    "0"         = creating first time slice')
disp('    "|"         = end of time for waveforms, continue using last defined time slice ')
disp('    "E INIT ->" = initialisation of the simulation in evolution mode')
disp('    "R"         = rewind to previous time slice')
disp('    "Z"         = same time slice than previous call')
disp('    "Ri-"       = time slice interpolation: rewind to previous time slice')
disp('    "Si-"       = time slice interpolation: same time slice than previous call')
disp('    "X"         = time slice interpolation: extend some data after last time slice (miss formated data)')
disp(' ')
disp('====================================================================')

